[General]
Aur_Tool_Name=yay
Backend=alpm
Distro_RSS_Url=https://archlinux.org/feeds/news/
Instant_Search=false
PackageList_Ordered_Col=0
PackageList_Sort_Order=0
Show_Groups_Panel=false
Use_Default_App_Icon=true
