general {
    col.active_border = rgba(998d9d77)
    col.inactive_border = rgba(4d435155)
}

misc {
    background_color = rgba(161219FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(161219FF)
        col.text = rgba(eadfeaFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(eadfea), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eadfea), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(eadfea), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrule = border_color rgba(78d7c1AA) rgba(78d7c177), match:pin 1
